server:
  port: 8081
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://10.50.99.50:32370/saga-order}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:Umee2021}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-order
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  kafka:
    consumer:
      group-id: order
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: 10.50.99.50:30001